-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-09-13 21:40:20 CLST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE CLIENTE 
    ( 
     id_cli        NUMBER (10)  NOT NULL , 
     nom_emp       VARCHAR2 (25)  NOT NULL , 
     correo        VARCHAR2 (50)  NOT NULL , 
     p_nom         VARCHAR2 (25) , 
     s_nom         VARCHAR2 (25) , 
     p_ape         VARCHAR2 (25) , 
     s_ape         VARCHAR2 (25) , 
     telefono      NUMBER (9) , 
     COMUNA_id_com NUMBER (5)  NOT NULL 
    ) 
;

ALTER TABLE CLIENTE 
    ADD CONSTRAINT CLIENTE_PK PRIMARY KEY ( id_cli ) ;

CREATE TABLE COMUNA 
    ( 
     id_com        NUMBER (5)  NOT NULL , 
     nom_com       VARCHAR2 (50)  NOT NULL , 
     REGION_id_reg NUMBER (2)  NOT NULL 
    ) 
;

ALTER TABLE COMUNA 
    ADD CONSTRAINT COMUNA_PK PRIMARY KEY ( id_com ) ;

CREATE TABLE COTIZACION 
    ( 
     id_coti        NUMBER (10)  NOT NULL , 
     fecha          DATE  NOT NULL , 
     monto_total    NUMBER (10,2)  NOT NULL , 
     estado         VARCHAR2 (10)  NOT NULL , 
     CLIENTE_id_cli NUMBER (10)  NOT NULL 
    ) 
;

ALTER TABLE COTIZACION 
    ADD CONSTRAINT COTIZACION_PK PRIMARY KEY ( id_coti ) ;

CREATE TABLE DET_ORDEN_COM 
    ( 
     id_det_com       NUMBER (10)  NOT NULL , 
     cantidad         NUMBER (4)  NOT NULL , 
     ORDEN_COM_id_ord NUMBER (10)  NOT NULL , 
     PRODUCTO_id_pro  NUMBER (6)  NOT NULL 
    ) 
;

ALTER TABLE DET_ORDEN_COM 
    ADD CONSTRAINT DET_ORDEN_COM_PK PRIMARY KEY ( id_det_com ) ;

CREATE TABLE DETALLE_COT 
    ( 
     id_det             NUMBER (10)  NOT NULL , 
     cantidad           NUMBER (4)  NOT NULL , 
     precio_unitario    NUMBER (10,2)  NOT NULL , 
     COTIZACION_id_coti NUMBER (10)  NOT NULL , 
     PRODUCTO_id_pro    NUMBER (6) 
    ) 
;

ALTER TABLE DETALLE_COT 
    ADD CONSTRAINT DETALLE_COT_PK PRIMARY KEY ( id_det ) ;

CREATE TABLE ORDEN_COM 
    ( 
     id_ord                 NUMBER (10)  NOT NULL , 
     fecha_pedido           DATE  NOT NULL , 
     estado_pedido          VARCHAR2 (10)  NOT NULL , 
     fecha_esperada_entrega DATE  NOT NULL , 
     PROVEEDOR_id_prov      NUMBER (6)  NOT NULL 
    ) 
;

ALTER TABLE ORDEN_COM 
    ADD CONSTRAINT ORDEN_COM_PK PRIMARY KEY ( id_ord ) ;

CREATE TABLE PRODUCTO 
    ( 
     id_pro  NUMBER (6)  NOT NULL , 
     nom_pro VARCHAR2 (50)  NOT NULL , 
     ref     NUMBER (6) 
    ) 
;

ALTER TABLE PRODUCTO 
    ADD CONSTRAINT PRODUCTO_PK PRIMARY KEY ( id_pro ) ;

CREATE TABLE PRODUCTO_PROVEEDOR 
    ( 
     PROVEEDOR_id_prov NUMBER (6)  NOT NULL , 
     PRODUCTO_id_pro   NUMBER (6)  NOT NULL 
    ) 
;

ALTER TABLE PRODUCTO_PROVEEDOR 
    ADD CONSTRAINT PRODUCTO_PROVEEDOR_PK PRIMARY KEY ( PROVEEDOR_id_prov, PRODUCTO_id_pro ) ;

CREATE TABLE PROVEEDOR 
    ( 
     id_prov       NUMBER (6)  NOT NULL , 
     nom_prov      VARCHAR2 (25)  NOT NULL , 
     COMUNA_id_com NUMBER (5)  NOT NULL 
    ) 
;

ALTER TABLE PROVEEDOR 
    ADD CONSTRAINT PROVEEDOR_PK PRIMARY KEY ( id_prov ) ;

CREATE TABLE REGION 
    ( 
     id_reg  NUMBER (2)  NOT NULL , 
     nom_reg VARCHAR2 (25)  NOT NULL 
    ) 
;

ALTER TABLE REGION 
    ADD CONSTRAINT REGION_PK PRIMARY KEY ( id_reg ) ;

ALTER TABLE CLIENTE 
    ADD CONSTRAINT CLIENTE_COMUNA_FK FOREIGN KEY 
    ( 
     COMUNA_id_com
    ) 
    REFERENCES COMUNA 
    ( 
     id_com
    ) 
;

ALTER TABLE COMUNA 
    ADD CONSTRAINT COMUNA_REGION_FK FOREIGN KEY 
    ( 
     REGION_id_reg
    ) 
    REFERENCES REGION 
    ( 
     id_reg
    ) 
;

ALTER TABLE COTIZACION 
    ADD CONSTRAINT COTIZACION_CLIENTE_FK FOREIGN KEY 
    ( 
     CLIENTE_id_cli
    ) 
    REFERENCES CLIENTE 
    ( 
     id_cli
    ) 
;

ALTER TABLE DET_ORDEN_COM 
    ADD CONSTRAINT DET_ORDEN_COM_ORDEN_COM_FK FOREIGN KEY 
    ( 
     ORDEN_COM_id_ord
    ) 
    REFERENCES ORDEN_COM 
    ( 
     id_ord
    ) 
;

ALTER TABLE DET_ORDEN_COM 
    ADD CONSTRAINT DET_ORDEN_COM_PRODUCTO_FK FOREIGN KEY 
    ( 
     PRODUCTO_id_pro
    ) 
    REFERENCES PRODUCTO 
    ( 
     id_pro
    ) 
;

ALTER TABLE DETALLE_COT 
    ADD CONSTRAINT DETALLE_COT_COTIZACION_FK FOREIGN KEY 
    ( 
     COTIZACION_id_coti
    ) 
    REFERENCES COTIZACION 
    ( 
     id_coti
    ) 
;

ALTER TABLE DETALLE_COT 
    ADD CONSTRAINT DETALLE_COT_PRODUCTO_FK FOREIGN KEY 
    ( 
     PRODUCTO_id_pro
    ) 
    REFERENCES PRODUCTO 
    ( 
     id_pro
    ) 
;

ALTER TABLE ORDEN_COM 
    ADD CONSTRAINT ORDEN_COM_PROVEEDOR_FK FOREIGN KEY 
    ( 
     PROVEEDOR_id_prov
    ) 
    REFERENCES PROVEEDOR 
    ( 
     id_prov
    ) 
;

ALTER TABLE PRODUCTO_PROVEEDOR 
    ADD CONSTRAINT PRODUCTO_PROVEEDOR_PRODUCTO_FK FOREIGN KEY 
    ( 
     PRODUCTO_id_pro
    ) 
    REFERENCES PRODUCTO 
    ( 
     id_pro
    ) 
;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE PRODUCTO_PROVEEDOR 
    ADD CONSTRAINT PRODUCTO_PROVEEDOR_PROVEEDOR_FK FOREIGN KEY 
    ( 
     PROVEEDOR_id_prov
    ) 
    REFERENCES PROVEEDOR 
    ( 
     id_prov
    ) 
;

ALTER TABLE PROVEEDOR 
    ADD CONSTRAINT PROVEEDOR_COMUNA_FK FOREIGN KEY 
    ( 
     COMUNA_id_com
    ) 
    REFERENCES COMUNA 
    ( 
     id_com
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                             0
-- ALTER TABLE                             21
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   1
-- WARNINGS                                 0
